[project]
name = "pecei"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Jason-skd", email = "wintor76111@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "anthropic>=0.121.0",
    "openai>=2.53.0",
    "pillow>=12.3.0",
    "pydantic>=2.13.4",
    "pygame-ce>=2.5.4",
    "pyyaml>=6.0.3",
]

[project.scripts]
pecei = "pecei:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
